#input_path: test_seed=0_factor=1.3_dist=20_bound+10_pred_obj # Can be a file or a folder
#save_dir: test_seed=0_factor=1.3_dist=20_bound+10_pred_vis_60

input_path: test_seed=0_factor=1.3_dist=20_bound+10_pred_obj/FA3_8L20221001_0401.obj
save_dir: TEST

color_scheme: # Colors must be in hex format
    # Bottom color
  - 0x00008A # Dark Blue
  - 0xFFD600 # Gold
  - 0x00ff28 # Light Orange
  - 0xff00df # Orange
  - 0xFF0000 # Bright Red
  # Top color


  """
    # Bottom color
  - 0x00008A # Dark Blue
  - 0xFFD600 # Gold
  - 0xFFC000 # Light Orange
  - 0xFF8C00 # Orange
  - 0xFF0000 # Bright Red
  # Top color
  """