program: train.py
command:
  - ${env}
  - ${interpreter} # Put path to pyhon.exe here
  - ${program}
  - "--config"
  - "cfg/config.yaml"
  - "--hyp"
  - ${args_json_file}
method: random
metric:
  goal: minimize
  name: "val_mse_loss"
parameters:
  learning_rate:
    min: 0
    max: 0.1
    distribution: uniform
  weight_decay:
    min: 1.0e-9
    max: 1.0e-6
    distribution: uniform
  batch_size:
    min: 16
    max: 128
    distribution: int_uniform
  patience:
    min: 20
    max: 40
    distribution: int_uniform
  epochs:
    min: 100
    max: 500
    distribution: int_uniform
