program: train.py
command:
  - ${env}
  - ${interpreter} # Put path to pyhon.exe here
  - ${program}
  - "--config"
  - "cfg/config.yaml"
  - "--hyp"
  - ${args_json_file}
method: random
metric:
  goal: minimize
  name: "val_mse_loss"
parameters:
  kernel_size:
    parameters:
      depth:
        min: 3
        max: 5
        distribution: int_uniform
      height:
        min: 3
        max: 5
        distribution: int_uniform
      width:
        value: 1
  stride:
    min: 1
    max: 10
    distribution: int_uniform
  padding:
    value: 0
  num_hidden_layers:
    min: 2
    max: 20
    distribution: int_uniform
  learning_rate:
    min: 0
    max: 0.1
    distribution: uniform
  weight_decay:
    min: 1.0e-9
    max: 1.0e-6
    distribution: uniform
  batch_size:
    min: 16
    max: 256
    distribution: int_uniform
  patience:
    min: 20
    max: 40
    distribution: int_uniform
  epochs:
    min: 5
    max: 10
    distribution: int_uniform
